name: Release

on:
    push:
        tags:
            - "*.*.*"

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            -   uses: actions/checkout@v2
            -   uses: actions/setup-node@v2
                with:
                    node-version: "18"

            -   name: install dependencies
                run: npm ci

            -   name: test
                run: npm test

            -   name: build
                run: npm run build

            -   name: create release
                uses: softprops/action-gh-release@v1
                if: startsWith(github.ref, 'refs/tags/')
                with:
                    files: |
                        temp/vault/.obsidian/plugins/labeled-annotations/main.js
                        temp/vault/.obsidian/plugins/labeled-annotations/styles.css
                        manifest.json
                    draft: true
                    prerelease: true
